module.exports = [
  {
    traceId: 'uZ6F+bY32eBVmrK0pvfWig==',
    id: '05NqQbS+w4M=',
    startTime: '2026-03-31T11:29:17.171Z',
    hrStartTime: 1774956557171000000n,
    name: 'middleware - query',
    kind: 'internal',
    parentSpanId: 'uvEyBf/Y6dA=',
    parent: { id: 'uvEyBf/Y6dA=', traceId: 'uZ6F+bY32eBVmrK0pvfWig==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.60.0',
      'express.name': 'query',
      'express.type': 'middleware',
      'span.kind': 'internal',
    },
  },
  {
    traceId: 'uZ6F+bY32eBVmrK0pvfWig==',
    id: 'Qb1uTaEDXKg=',
    startTime: '2026-03-31T11:29:17.172Z',
    hrStartTime: 1774956557172000000n,
    name: 'middleware - expressInit',
    kind: 'internal',
    parentSpanId: 'uvEyBf/Y6dA=',
    parent: { id: 'uvEyBf/Y6dA=', traceId: 'uZ6F+bY32eBVmrK0pvfWig==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.60.0',
      'express.name': 'expressInit',
      'express.type': 'middleware',
      'span.kind': 'internal',
    },
  },
  {
    traceId: 'uZ6F+bY32eBVmrK0pvfWig==',
    id: '9UeRdVL+xRQ=',
    startTime: '2026-03-31T11:29:17.194Z',
    hrStartTime: 1774956557194000000n,
    name: 'middleware - query',
    kind: 'internal',
    parentSpanId: 'Ylm3Ki2Etgg=',
    parent: { id: 'Ylm3Ki2Etgg=', traceId: 'uZ6F+bY32eBVmrK0pvfWig==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.60.0',
      'express.name': 'query',
      'express.type': 'middleware',
      'span.kind': 'internal',
    },
  },
  {
    traceId: 'uZ6F+bY32eBVmrK0pvfWig==',
    id: 'z/UM0BT4PxM=',
    startTime: '2026-03-31T11:29:17.195Z',
    hrStartTime: 1774956557195000000n,
    name: 'middleware - expressInit',
    kind: 'internal',
    parentSpanId: 'Ylm3Ki2Etgg=',
    parent: { id: 'Ylm3Ki2Etgg=', traceId: 'uZ6F+bY32eBVmrK0pvfWig==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.60.0',
      'express.name': 'expressInit',
      'express.type': 'middleware',
      'span.kind': 'internal',
    },
  },
  {
    traceId: 'uZ6F+bY32eBVmrK0pvfWig==',
    id: 'm+V6gSPKv1k=',
    startTime: '2026-03-31T11:29:17.195Z',
    hrStartTime: 1774956557195000000n,
    name: 'request handler - /name',
    kind: 'internal',
    parentSpanId: 'Ylm3Ki2Etgg=',
    parent: { id: 'Ylm3Ki2Etgg=', traceId: 'uZ6F+bY32eBVmrK0pvfWig==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.60.0',
      'http.route': '/name',
      'express.name': '/name',
      'express.type': 'request_handler',
      'span.kind': 'internal',
    },
  },
  {
    traceId: 'uZ6F+bY32eBVmrK0pvfWig==',
    id: 'yv8yVExhSk8=',
    startTime: '2026-03-31T11:29:17.172Z',
    hrStartTime: 1774956557172000000n,
    name: 'request handler - /animal',
    kind: 'internal',
    parentSpanId: 'uvEyBf/Y6dA=',
    parent: { id: 'uvEyBf/Y6dA=', traceId: 'uZ6F+bY32eBVmrK0pvfWig==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.60.0',
      'http.route': '/animal',
      'express.name': '/animal',
      'express.type': 'request_handler',
      'span.kind': 'internal',
    },
  },
  {
    traceId: 'uZ6F+bY32eBVmrK0pvfWig==',
    id: 'vMjJ40vf1iE=',
    startTime: '2026-03-31T11:29:17.187Z',
    hrStartTime: 1774956557187000000n,
    name: 'tcp.connect',
    kind: 'internal',
    parentSpanId: 'yv8yVExhSk8=',
    parent: { id: 'yv8yVExhSk8=', traceId: 'uZ6F+bY32eBVmrK0pvfWig==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-net',
      'otel.scope.version': '0.56.0',
      'network.transport': 'tcp',
      'server.address': 'localhost',
      'server.port': undefined,
      'network.peer.address': '::1',
      'network.local.address': '::1',
      'network.local.port': undefined,
      'span.kind': 'internal',
    },
  },
  {
    traceId: 'uZ6F+bY32eBVmrK0pvfWig==',
    id: 'Ylm3Ki2Etgg=',
    startTime: '2026-03-31T11:29:17.194Z',
    hrStartTime: 1774956557194000000n,
    name: 'GET /name',
    kind: 'server',
    parentSpanId: 'quFiWOe94AI=',
    parent: { id: 'quFiWOe94AI=', traceId: 'uZ6F+bY32eBVmrK0pvfWig==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-http',
      'otel.scope.version': '0.212.0',
      'http.request.method': 'GET',
      'url.scheme': 'http',
      'url.path': '/name',
      'server.address': 'localhost',
      'server.port': undefined,
      'network.peer.address': '::1',
      'network.peer.port': undefined,
      'network.protocol.version': '1.1',
      'user_agent.original': 'node',
      'client.address': '::1',
      'http.response.status_code': undefined,
      'http.route': '/name',
      'span.kind': 'server',
    },
  },
  {
    traceId: 'uZ6F+bY32eBVmrK0pvfWig==',
    id: 'uvEyBf/Y6dA=',
    startTime: '2026-03-31T11:29:17.169Z',
    hrStartTime: 1774956557169000000n,
    name: 'GET /animal',
    kind: 'server',
    parentSpanId: undefined,
    parent: undefined,
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-http',
      'otel.scope.version': '0.212.0',
      'http.request.method': 'GET',
      'url.scheme': 'http',
      'url.path': '/animal',
      'server.address': 'app',
      'server.port': undefined,
      'network.peer.address': '::ffff:172.20.0.4',
      'network.peer.port': undefined,
      'network.protocol.version': '1.1',
      'user_agent.original': 'node',
      'client.address': '::ffff:172.20.0.4',
      'http.response.status_code': undefined,
      'http.route': '/animal',
      'span.kind': 'server',
    },
  },
  {
    traceId: 'uZ6F+bY32eBVmrK0pvfWig==',
    id: 'quFiWOe94AI=',
    startTime: '2026-03-31T11:29:17.186Z',
    hrStartTime: 1774956557186000000n,
    name: 'GET',
    kind: 'client',
    parentSpanId: 'yv8yVExhSk8=',
    parent: { id: 'yv8yVExhSk8=', traceId: 'uZ6F+bY32eBVmrK0pvfWig==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-undici',
      'otel.scope.version': '0.22.0',
      'http.request.method': 'GET',
      'http.request.method_original': 'GET',
      'url.full': 'http://localhost/name',
      'url.path': '/name',
      'url.query': undefined,
      'url.scheme': 'http',
      'server.address': 'localhost',
      'server.port': undefined,
      'user_agent.original': 'node',
      'network.peer.address': '::1',
      'network.peer.port': undefined,
      'http.response.status_code': undefined,
      'span.kind': 'client',
    },
  },
];
