module.exports = [
  {
    traceId: 'c5zIzB9SgNYhBPCbTjwg4A==',
    id: 'u2UfqEE6o2g=',
    startTime: '2024-10-23T12:08:56.957Z',
    hrStartTime: 1729685336957000000n,
    name: 'middleware - query',
    kind: 'internal',
    parentSpanId: 'EjUwbQetNus=',
    parent: { id: 'EjUwbQetNus=', traceId: 'c5zIzB9SgNYhBPCbTjwg4A==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.42.0',
      'http.route': '/',
      'express.name': 'query',
      'express.type': 'middleware',
      'span.kind': 'internal'
    }
  },
  {
    traceId: 'c5zIzB9SgNYhBPCbTjwg4A==',
    id: 'th00mL0dypQ=',
    startTime: '2024-10-23T12:08:56.960Z',
    hrStartTime: 1729685336960000000n,
    name: 'middleware - expressInit',
    kind: 'internal',
    parentSpanId: 'EjUwbQetNus=',
    parent: { id: 'EjUwbQetNus=', traceId: 'c5zIzB9SgNYhBPCbTjwg4A==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.42.0',
      'http.route': '/',
      'express.name': 'expressInit',
      'express.type': 'middleware',
      'span.kind': 'internal'
    }
  },
  {
    traceId: 'c5zIzB9SgNYhBPCbTjwg4A==',
    id: '1Er5vsUvUVg=',
    startTime: '2024-10-23T12:08:56.961Z',
    hrStartTime: 1729685336961000000n,
    name: 'request handler - /animal',
    kind: 'internal',
    parentSpanId: 'EjUwbQetNus=',
    parent: { id: 'EjUwbQetNus=', traceId: 'c5zIzB9SgNYhBPCbTjwg4A==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.42.0',
      'http.route': '/animal',
      'express.name': '/animal',
      'express.type': 'request_handler',
      'span.kind': 'internal'
    }
  },
  {
    traceId: 'c5zIzB9SgNYhBPCbTjwg4A==',
    id: 'n6/1kjZEBD4=',
    startTime: '2024-10-23T12:08:56.980Z',
    hrStartTime: 1729685336980000000n,
    name: 'middleware - query',
    kind: 'internal',
    parentSpanId: '4A4ribbJejI=',
    parent: { id: '4A4ribbJejI=', traceId: 'c5zIzB9SgNYhBPCbTjwg4A==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.42.0',
      'http.route': '/',
      'express.name': 'query',
      'express.type': 'middleware',
      'span.kind': 'internal'
    }
  },
  {
    traceId: 'c5zIzB9SgNYhBPCbTjwg4A==',
    id: '7Fogi1oddwA=',
    startTime: '2024-10-23T12:08:56.981Z',
    hrStartTime: 1729685336981000000n,
    name: 'middleware - expressInit',
    kind: 'internal',
    parentSpanId: '4A4ribbJejI=',
    parent: { id: '4A4ribbJejI=', traceId: 'c5zIzB9SgNYhBPCbTjwg4A==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.42.0',
      'http.route': '/',
      'express.name': 'expressInit',
      'express.type': 'middleware',
      'span.kind': 'internal'
    }
  },
  {
    traceId: 'c5zIzB9SgNYhBPCbTjwg4A==',
    id: '+qi2mdPafOY=',
    startTime: '2024-10-23T12:08:56.981Z',
    hrStartTime: 1729685336981000000n,
    name: 'request handler - /name',
    kind: 'internal',
    parentSpanId: '4A4ribbJejI=',
    parent: { id: '4A4ribbJejI=', traceId: 'c5zIzB9SgNYhBPCbTjwg4A==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.42.0',
      'http.route': '/name',
      'express.name': '/name',
      'express.type': 'request_handler',
      'span.kind': 'internal'
    }
  },
  {
    traceId: 'c5zIzB9SgNYhBPCbTjwg4A==',
    id: 'awOi2E+05aU=',
    startTime: '2024-10-23T12:08:56.972Z',
    hrStartTime: 1729685336972000000n,
    name: 'tcp.connect',
    kind: 'internal',
    parentSpanId: '8ROHwPYvo4Q=',
    parent: { id: '8ROHwPYvo4Q=', traceId: 'c5zIzB9SgNYhBPCbTjwg4A==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-net',
      'otel.scope.version': '0.39.0',
      'net.transport': 'ip_tcp',
      'net.peer.name': 'localhost',
      'net.peer.port': '80',
      'net.peer.ip': '::1',
      'net.host.ip': '::1',
      'net.host.port': undefined,
      'span.kind': 'internal'
    }
  },
  {
    traceId: 'c5zIzB9SgNYhBPCbTjwg4A==',
    id: '4A4ribbJejI=',
    startTime: '2024-10-23T12:08:56.980Z',
    hrStartTime: 1729685336980000000n,
    name: 'GET /name',
    kind: 'server',
    parentSpanId: '8ROHwPYvo4Q=',
    parent: { id: '8ROHwPYvo4Q=', traceId: 'c5zIzB9SgNYhBPCbTjwg4A==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-http',
      'otel.scope.version': '0.53.0',
      'http.url': 'http://localhost/name',
      'http.host': 'localhost',
      'net.host.name': 'localhost',
      'http.method': 'GET',
      'http.scheme': 'http',
      'http.target': '/name',
      'http.user_agent': 'axios/0.28.1',
      'http.flavor': '1.1',
      'net.transport': 'ip_tcp',
      'net.host.ip': '::1',
      'net.host.port': undefined,
      'net.peer.ip': '::1',
      'net.peer.port': undefined,
      'http.status_code': undefined,
      'http.status_text': 'OK',
      'http.route': '/name',
      'span.kind': 'server'
    }
  },
  {
    traceId: 'c5zIzB9SgNYhBPCbTjwg4A==',
    id: '8ROHwPYvo4Q=',
    startTime: '2024-10-23T12:08:56.969Z',
    hrStartTime: 1729685336969000000n,
    name: 'GET',
    kind: 'client',
    parentSpanId: 'EjUwbQetNus=',
    parent: { id: 'EjUwbQetNus=', traceId: 'c5zIzB9SgNYhBPCbTjwg4A==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-http',
      'otel.scope.version': '0.53.0',
      'http.url': 'http://localhost/name',
      'http.method': 'GET',
      'http.target': '/name',
      'net.peer.name': 'localhost',
      'http.host': 'localhost:80',
      'net.peer.ip': '::1',
      'net.peer.port': undefined,
      'http.response_content_length_uncompressed': undefined,
      'http.status_code': undefined,
      'http.status_text': 'OK',
      'http.flavor': '1.1',
      'net.transport': 'ip_tcp',
      'span.kind': 'client'
    }
  },
  {
    traceId: 'c5zIzB9SgNYhBPCbTjwg4A==',
    id: 'EjUwbQetNus=',
    startTime: '2024-10-23T12:08:56.944Z',
    hrStartTime: 1729685336944000000n,
    name: 'GET /animal',
    kind: 'server',
    parentSpanId: undefined,
    parent: undefined,
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-http',
      'otel.scope.version': '0.53.0',
      'http.url': 'http://app/animal',
      'http.host': 'app',
      'net.host.name': 'app',
      'http.method': 'GET',
      'http.scheme': 'http',
      'http.target': '/animal',
      'http.user_agent': 'node',
      'http.flavor': '1.1',
      'net.transport': 'ip_tcp',
      'net.host.ip': '::ffff:172.18.0.3',
      'net.host.port': undefined,
      'net.peer.ip': '::ffff:172.18.0.4',
      'net.peer.port': undefined,
      'http.status_code': undefined,
      'http.status_text': 'OK',
      'http.route': '/animal',
      'span.kind': 'server'
    }
  }
];
