# Example configuration file for Splunk OpenTelemetry Node.js Agent Manager
# Copy this file to ~/.splunk-otel-manager.yaml and customize as needed

# Agent installation settings
dest_folder: "/opt/splunk-nodejs-agent"
backup_folder: "/opt/splunk-nodejs-agent/backup"
agent_version: "latest"  # Can be "latest" or specific version like "1.0.0"

# Splunk configuration
access_token: "YOUR_SPLUNK_ACCESS_TOKEN_HERE"
otlp_endpoint: "https://ingest.us1.signalfx.com/v2/trace"

# NPM settings
npm_registry: "https://registry.npmjs.org"

# Agent node configuration
agent_node_name: "my-node"
no_node_name_suffix: false  # If true, won't add "-0" suffix to node name

# Backup settings
keep_backup: true  # Keep backup files after uninstall
