---
- name: Agent Rollback
  become: true
  block:
    - name: Common agent rollback part
      block:
        - name: Check if splunk-agent-version exists in backup
          ansible.builtin.stat:
            path: "{{ node_agent_backup_folder }}/splunk-agent-version.txt"
          register: backup_splunk_version_exists

        - name: Check if backup config exists
          ansible.builtin.stat:
            path: "{{ node_agent_backup_folder }}/splunk-config.js"
          register: backup_config_exists

        - name: Restore splunk-config.js file in case it exists
          ansible.builtin.shell: "cp {{ node_agent_backup_folder }}/splunk-config.js {{ node_agent_dest_folder }}/"
          when: backup_config_exists.stat.exists

        - name: Read the backed-up version of Splunk Node.js agent
          ansible.builtin.slurp:
            src: "{{ node_agent_backup_folder }}/splunk-agent-version.txt"
          register: node_backup_version

        - name: Run npm install on restored Splunk Node.js agent version
          ansible.builtin.npm:
            name: splunk-agent
            version: "{{ node_backup_version['content'] | b64decode | regex_replace('^[~^]+', '') }}"
            path: "{{ node_agent_dest_folder }}"
            state: present
          when: backup_splunk_version_exists.stat.exists

        - name: splunk_agent_status Node.js agent restored successfully
          ansible.builtin.debug:
            msg: '{ "agentRollback": "Splunk Node.js agent was restored successfully" }'

        - name: Agent rollback result set fact
          ansible.builtin.set_fact:
            agent_result:
              error: false
              install_path: "{{ node_agent_dest_folder }}"
              agent_type: "node"
              action: "rollback"

        - name: splunk.agent.result
          ansible.builtin.debug:
            msg: "{{ agent_result | to_json }}"

  rescue:
    - name: splunk_agent_status Rollback Task Failed
      ansible.builtin.debug:
        msg: '{ "agentRollback": "Error occurred while reinstalling agent with backup." }'

    - name: Set Node Agent Result Fact
      ansible.builtin.set_fact:
        splunk_agent_result:
          error: true
          install_path: null
          agent_type: "node"
          agent_version: null
          action: "rollback"

    - name: splunk.agent.result
      ansible.builtin.debug:
        msg: "{{ splunk_agent_result | to_json }}"