---
- name: Ensure Node.js is installed
  ansible.builtin.package:
    name: nodejs
    state: present
  become: true
  when: ansible_os_family != "Darwin"

# - name: Ensure Node.js is installed (Mac)
#   ansible.builtin.homebrew:
#     name: node
#     state: present
#   when: ansible_os_family == "Darwin"

- name: Ensure npm is installed (Linux)
  ansible.builtin.package:
    name: npm
    state: present
  become: true
  when: ansible_os_family != "Darwin"

- name: Check node version
  ansible.builtin.command: node --version
  register: node_version
  changed_when: false
  failed_when: false

- name: Check npm version
  ansible.builtin.command: npm --version
  register: npm_version
  changed_when: false
  failed_when: false

- name: Show Node.js version
  ansible.builtin.debug:
    msg: "Node.js version: {{ node_version.stdout | default('not installed') }}"

- name: Show npm version
  ansible.builtin.debug:
    msg: "npm version: {{ npm_version.stdout | default('not installed') }}"