module.exports = [
  {
    traceId: '53KrOcBQVVYj2VgJ26ACcA==',
    id: 'Dz6x7tP6Eg4=',
    startTime: '2025-10-22T11:04:23.308Z',
    hrStartTime: 1761131063308000000n,
    name: 'middleware - query',
    kind: 'internal',
    parentSpanId: '96vR6IwdTzQ=',
    parent: { id: '96vR6IwdTzQ=', traceId: '53KrOcBQVVYj2VgJ26ACcA==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.47.1',
      'http.route': '/',
      'express.name': 'query',
      'express.type': 'middleware',
      'span.kind': 'internal',
    },
  },
  {
    traceId: '53KrOcBQVVYj2VgJ26ACcA==',
    id: '3Gi+ARkkOC0=',
    startTime: '2025-10-22T11:04:23.308Z',
    hrStartTime: 1761131063308000000n,
    name: 'middleware - expressInit',
    kind: 'internal',
    parentSpanId: '96vR6IwdTzQ=',
    parent: { id: '96vR6IwdTzQ=', traceId: '53KrOcBQVVYj2VgJ26ACcA==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.47.1',
      'http.route': '/',
      'express.name': 'expressInit',
      'express.type': 'middleware',
      'span.kind': 'internal',
    },
  },
  {
    traceId: '53KrOcBQVVYj2VgJ26ACcA==',
    id: 'tdag4T9pqyc=',
    startTime: '2025-10-22T11:04:23.309Z',
    hrStartTime: 1761131063309000000n,
    name: 'request handler - /main',
    kind: 'internal',
    parentSpanId: '96vR6IwdTzQ=',
    parent: { id: '96vR6IwdTzQ=', traceId: '53KrOcBQVVYj2VgJ26ACcA==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.47.1',
      'http.route': '/main',
      'express.name': '/main',
      'express.type': 'request_handler',
      'span.kind': 'internal',
    },
  },
  {
    traceId: '53KrOcBQVVYj2VgJ26ACcA==',
    id: 'VTw/v/yOmy0=',
    startTime: '2025-10-22T11:04:23.309Z',
    hrStartTime: 1761131063309000000n,
    name: 'main',
    kind: 'internal',
    parentSpanId: '96vR6IwdTzQ=',
    parent: { id: '96vR6IwdTzQ=', traceId: '53KrOcBQVVYj2VgJ26ACcA==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': 'splunk-otel-example-esbuild-cjs',
      'span.kind': 'internal',
    },
  },
  {
    traceId: '53KrOcBQVVYj2VgJ26ACcA==',
    id: '96vR6IwdTzQ=',
    startTime: '2025-10-22T11:04:23.307Z',
    hrStartTime: 1761131063307000000n,
    name: 'GET /main',
    kind: 'server',
    parentSpanId: undefined,
    parent: undefined,
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-http',
      'otel.scope.version': '0.203.0',
      'http.request.method': 'GET',
      'url.scheme': 'http',
      'url.path': '/main',
      'server.address': 'app',
      'server.port': undefined,
      'network.peer.address': '::ffff:172.20.0.4',
      'network.peer.port': undefined,
      'network.protocol.version': '1.1',
      'user_agent.original': 'node',
      'client.address': '::ffff:172.20.0.4',
      'http.response.status_code': undefined,
      'http.route': '/main',
      'span.kind': 'server',
    },
  },
];
