// a console.log from a previous run
module.exports = [
  {
    traceId: 'VlRfCOMPRqQs5pkzwwgEGQ==',
    id: 'RO/3VuV9hMU=',
    startTime: '2025-04-25T07:23:12.271Z',
    hrStartTime: 1745565792271000000n,
    name: 'work',
    kind: 'internal',
    parentSpanId: 'NV6Lo+dFbkQ=',
    parent: { id: 'NV6Lo+dFbkQ=', traceId: 'VlRfCOMPRqQs5pkzwwgEGQ==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': 'splunk-otel-example-mixed',
      'work.expected_duration': undefined,
      'work.my_parameter': undefined,
      'work.result': undefined,
      'span.kind': 'internal',
    },
  },
  {
    traceId: 'VlRfCOMPRqQs5pkzwwgEGQ==',
    id: 'NV6Lo+dFbkQ=',
    startTime: '2025-04-25T07:23:12.270Z',
    hrStartTime: 1745565792270000000n,
    name: 'GET',
    kind: 'server',
    parentSpanId: undefined,
    parent: undefined,
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-http',
      'otel.scope.version': '0.200.0',
      'http.request.method': 'GET',
      'url.scheme': 'http',
      'url.path': '/',
      'server.address': 'app',
      'server.port': undefined,
      'network.peer.address': '::ffff:172.20.0.4',
      'network.peer.port': undefined,
      'network.protocol.version': '1.1',
      'user_agent.original': 'node',
      'client.address': '::ffff:172.20.0.4',
      'http.response.status_code': undefined,
      'span.kind': 'server',
    },
  },
];
