---
galaxy_info:
  author: Splunk Inc.
  description: Splunk OpenTelemetry Node.js Agent management using Go module
  company: Splunk Inc.
  
  license: Apache-2.0
  
  min_ansible_version: 2.9
  
  platforms:
    - name: Ubuntu
      versions:
        - bionic
        - focal
        - jammy
    - name: CentOS
      versions:
        - 7
        - 8
    - name: RedHat
      versions:
        - 7
        - 8
        - 9
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: MacOSX
      versions:
        - all

  galaxy_tags:
    - splunk
    - opentelemetry
    - observability
    - monitoring
    - nodejs
    - agent

dependencies: []
