---
- name: Manage Splunk Node.js Agent (Go-based)
  hosts: localhost
  become: false
  vars:
    # Main action variable - change this to: install, uninstall, rollback, upgrade
    agent_action: install
    
    # Agent configuration
    agent_version: "latest"
    splunk_access_token: "PeZlDQLdXr3zDMmm9vWW_g"
    otel_exporter_otlp_endpoint: "https://ingest.us1.signalfx.com/v2/trace"
    
    # Installation paths
    splunk_dest_folder: "/tmp/splunk-nodejs-agent"
    splunk_backup_folder: ""  # Leave empty to use default
    
    # Other settings
    keep_backup: true
    npm_registry: "https://registry.npmjs.org"
    agent_node_name: ""
    no_node_name_suffix: false
    
    # Go binary path
    go_binary_path: "/Users/abhinama/Documents/splunk/splunk-otel-js/go-module/bin/splunk-otel-manager"
  
  tasks:
    - name: "{{ agent_action | title }} Splunk Node.js Agent using Go module"
      ansible.builtin.command:
        cmd: >
          {{ go_binary_path }} {{ agent_action }}
          --dest-folder "{{ splunk_dest_folder }}"
          {% if agent_version %}--version "{{ agent_version }}"{% endif %}
          {% if splunk_access_token %}--access-token "{{ splunk_access_token }}"{% endif %}
          {% if otel_exporter_otlp_endpoint %}--otlp-endpoint "{{ otel_exporter_otlp_endpoint }}"{% endif %}
          {% if splunk_backup_folder %}--backup-folder "{{ splunk_backup_folder }}"{% endif %}
          {% if npm_registry %}--npm-registry "{{ npm_registry }}"{% endif %}
          {% if agent_node_name %}--node-name "{{ agent_node_name }}"{% endif %}
          {% if no_node_name_suffix %}--no-node-name-suffix{% endif %}
          {% if not keep_backup %}--keep-backup=false{% endif %}
          --verbose
      register: go_result
      changed_when: true
    
    - name: Display operation result
      ansible.builtin.debug:
        msg: "{{ go_result.stdout }}"
    
    - name: Parse JSON result
      ansible.builtin.set_fact:
        agent_result: "{{ go_result.stdout | from_json }}"
      when: go_result.stdout != ""
    
    - name: Display parsed agent result
      ansible.builtin.debug:
        var: agent_result
      when: agent_result is defined
    
    - name: Show operation summary
      ansible.builtin.debug:
        msg: |
          ========================================
          Splunk Node.js Agent {{ agent_action | title }} Complete
          ========================================
          Action: {{ agent_result.action | default(agent_action) }}
          Status: {{ 'SUCCESS' if not (agent_result.error | default(false)) else 'FAILED' }}
          Install Path: {{ agent_result.install_path | default('N/A') }}
          Agent Version: {{ agent_result.agent_version | default('N/A') }}
          Message: {{ agent_result.message | default('No message') }}
          ========================================
      when: agent_result is defined
