version: "3"
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.50.0
    environment:
      - SPLUNK_ACCESS_TOKEN
      - SPLUNK_REALM
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "9943:9943"   # signalfx
      - "4317:4317"   # otlp
