services:
  otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:0.111.0
    environment:
      - SPLUNK_CONFIG: /etc/otel/config.yml
      - SPLUNK_ACCESS_TOKEN
      - SPLUNK_REALM
    volumes:
      - ./collector.config.yml:/etc/otel/config.yml
    ports:
      - "4318:4318"   # otlp
