module.exports = [
  {
    traceId: 'H5yEgwBZEIhWo6aSFVNMhw==',
    id: 'LXA03SJRHDQ=',
    startTime: '2025-04-25T07:30:31.059Z',
    hrStartTime: 1745566231059000000n,
    name: 'middleware - query',
    kind: 'internal',
    parentSpanId: 'BYp4p1vcsvY=',
    parent: { id: 'BYp4p1vcsvY=', traceId: 'H5yEgwBZEIhWo6aSFVNMhw==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.48.1',
      'express.name': 'query',
      'express.type': 'middleware',
      'span.kind': 'internal',
    },
  },
  {
    traceId: 'H5yEgwBZEIhWo6aSFVNMhw==',
    id: '6LnXzzwPue0=',
    startTime: '2025-04-25T07:30:31.059Z',
    hrStartTime: 1745566231059000000n,
    name: 'middleware - expressInit',
    kind: 'internal',
    parentSpanId: 'BYp4p1vcsvY=',
    parent: { id: 'BYp4p1vcsvY=', traceId: 'H5yEgwBZEIhWo6aSFVNMhw==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.48.1',
      'express.name': 'expressInit',
      'express.type': 'middleware',
      'span.kind': 'internal',
    },
  },
  {
    traceId: 'H5yEgwBZEIhWo6aSFVNMhw==',
    id: 'XY4BEnnqUDA=',
    startTime: '2025-04-25T07:30:31.059Z',
    hrStartTime: 1745566231059000000n,
    name: 'request handler - /',
    kind: 'internal',
    parentSpanId: 'BYp4p1vcsvY=',
    parent: { id: 'BYp4p1vcsvY=', traceId: 'H5yEgwBZEIhWo6aSFVNMhw==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-express',
      'otel.scope.version': '0.48.1',
      'http.route': '/',
      'express.name': '/',
      'express.type': 'request_handler',
      'span.kind': 'internal',
    },
  },
  {
    traceId: 'H5yEgwBZEIhWo6aSFVNMhw==',
    id: 'waJXy75/5gw=',
    startTime: '2025-04-25T07:30:31.060Z',
    hrStartTime: 1745566231060000000n,
    name: 'calculate-random',
    kind: 'internal',
    parentSpanId: 'XY4BEnnqUDA=',
    parent: { id: 'XY4BEnnqUDA=', traceId: 'H5yEgwBZEIhWo6aSFVNMhw==' },
    status: { code: undefined },
    attributes: {
      'otel.scope.name': 'rng-app',
      'random-result': undefined,
      'random-method': 'diceroll',
      'span.kind': 'internal',
    },
  },
  {
    traceId: 'H5yEgwBZEIhWo6aSFVNMhw==',
    id: 'BYp4p1vcsvY=',
    startTime: '2025-04-25T07:30:31.057Z',
    hrStartTime: 1745566231057000000n,
    name: 'GET /',
    kind: 'server',
    parentSpanId: undefined,
    parent: undefined,
    status: { code: undefined },
    attributes: {
      'otel.scope.name': '@opentelemetry/instrumentation-http',
      'otel.scope.version': '0.200.0',
      'http.request.method': 'GET',
      'url.scheme': 'http',
      'url.path': '/',
      'server.address': 'app',
      'server.port': undefined,
      'network.peer.address': '::ffff:172.20.0.4',
      'network.peer.port': undefined,
      'network.protocol.version': '1.1',
      'user_agent.original': 'node',
      'client.address': '::ffff:172.20.0.4',
      'http.response.status_code': undefined,
      'http.route': '/',
      'span.kind': 'server',
    },
  },
];
