---
# Defaults file for Splunk Node.js Agent (Go-based)

# Path to the Go binary
go_binary_path: "/usr/local/bin/splunk-otel-manager"

# Agent directory permissions
agent_dir_permission:
  user: "{{ appdynamics_user | default('splunk') }}"
  group: "{{ appdynamics_group }}"

create_splunk_user: true

# Agent configuration-specific details
agent_dir: "{{ linux_custom_agent_install_path | default(splunk_dest_folder) }}"

splunk_dest_folder: /opt/splunk-nodejs-agent
splunk_backup_folder: /opt/splunk-nodejs-agent/backup

install_agent_from: "https://registry.npmjs.org/"
npm_registry: "https://registry.npmjs.org"

install_string: install
upgrade_string: upgrade

keep_backup: true  # Override to avoid deleting backup files while uninstalling

# Default agent version
agent_version: latest
