#!/usr/bin/env sh

PKG=$1
echo "Installing in all examples: $PKG"

for d in ./examples/*/ ; do
  if [ -f "$d/package.json" ]; then
    echo "$d"
    (
      cd "$d";
      npm install $PKG
    )
  fi
done

for d in ./examples/esbuild/*/ ; do
  if [ -f "$d/package.json" ]; then
    echo "$d"
    (
      cd "$d";
      npm install
    )
  fi
done