# Set up the environment, install deps
FROM node:16-alpine as base
RUN apk add g++ make python3

USER node
ENV TZ=UTC
RUN mkdir /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node [ \
	"binding.gyp", \
	"package*.json", \
	"*.lock", \
	"./" \
]
COPY --chown=node:node ["./scripts/examples-npm-install", "./scripts/examples-npm-install"]
COPY --chown=node:node ["./src/native_ext", "./src/native_ext"]
RUN npm install --omit peer

COPY --chown=node:node ./ .


# Install deps for examples
FROM base as published

RUN ./scripts/examples-npm-install

## Project root doesn't have start script defined
## Working dir(-w) must be provided to one of the example dirs
CMD ["npm", "run", "start"]


# Compile the package and use it in examples
FROM published as compiled

# use a single prebuild for tests so we don't have to compile it each install
RUN npm run prebuild:current
RUN npm run compile
RUN mv `npm pack` /tmp/splunk-otel.tgz
RUN ./scripts/examples-npm-install /tmp/splunk-otel.tgz
