/*
 * Copyright Splunk Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { Resource } from '@opentelemetry/resources';

export type LogLevel = 'none' | 'verbose' | 'debug' | 'info' | 'warn' | 'error';

export type ResourceFactory = (resource: Resource) => Resource;

export type EnvVarKey =
  | 'OTEL_ATTRIBUTE_COUNT_LIMIT'
  | 'OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT'
  | 'OTEL_EXPERIMENTAL_CONFIG_FILE'
  | 'OTEL_EXPORTER_OTLP_CERTIFICATE'
  | 'OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE'
  | 'OTEL_EXPORTER_OTLP_CLIENT_KEY'
  | 'OTEL_EXPORTER_OTLP_ENDPOINT'
  | 'OTEL_EXPORTER_OTLP_METRICS_ENDPOINT'
  | 'OTEL_EXPORTER_OTLP_METRICS_PROTOCOL'
  | 'OTEL_EXPORTER_OTLP_PROTOCOL'
  | 'OTEL_EXPORTER_OTLP_TRACES_ENDPOINT'
  | 'OTEL_EXPORTER_OTLP_TRACES_PROTOCOL'
  | 'OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED'
  | 'OTEL_LOG_LEVEL'
  | 'OTEL_LOGS_EXPORTER'
  | 'OTEL_METRIC_EXPORT_INTERVAL'
  | 'OTEL_METRICS_EXPORTER'
  | 'OTEL_PROPAGATORS'
  | 'OTEL_SERVICE_NAME'
  | 'OTEL_SPAN_LINK_COUNT_LIMIT'
  | 'OTEL_TRACES_EXPORTER'
  | 'OTEL_TRACES_SAMPLER'
  | 'SPLUNK_ACCESS_TOKEN'
  | 'SPLUNK_AUTOINSTRUMENT_PACKAGE_NAMES'
  | 'SPLUNK_AUTOMATIC_LOG_COLLECTION'
  | 'SPLUNK_DEBUG_METRICS_ENABLED'
  | 'SPLUNK_GRAPHQL_RESOLVE_SPANS_ENABLED'
  | 'SPLUNK_INSTRUMENTATION_METRICS_ENABLED'
  | 'SPLUNK_METRICS_ENABLED'
  | 'SPLUNK_NEXTJS_FIX_ENABLED'
  | 'SPLUNK_PROFILER_CALL_STACK_INTERVAL'
  | 'SPLUNK_PROFILER_ENABLED'
  | 'SPLUNK_PROFILER_LOGS_ENDPOINT'
  | 'SPLUNK_CPU_PROFILER_COLLECTION_INTERVAL'
  | 'SPLUNK_PROFILER_MEMORY_ENABLED'
  | 'SPLUNK_REALM'
  | 'SPLUNK_REDIS_INCLUDE_COMMAND_ARGS'
  | 'SPLUNK_RUNTIME_METRICS_COLLECTION_INTERVAL'
  | 'SPLUNK_RUNTIME_METRICS_ENABLED'
  | 'SPLUNK_SNAPSHOT_PROFILER_ENABLED'
  | 'SPLUNK_SNAPSHOT_PROFILER_SAMPLING_INTERVAL' // @deprecated To be removed in 5.0.
  | 'SPLUNK_SNAPSHOT_SAMPLING_INTERVAL'
  | 'SPLUNK_SNAPSHOT_SELECTION_PROBABILITY'
  | 'SPLUNK_SNAPSHOT_SELECTION_RATE' // @deprecated To be removed in 5.0.
  | 'SPLUNK_TRACE_RESPONSE_HEADER_ENABLED'
  | 'SPLUNK_TRACING_ENABLED';
