name: Lint
on: pull_request
permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch base_ref
        run: git fetch origin ${{ github.base_ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install npm dependencies
        run: npm ci --ignore-scripts
      - name: Check version
        run: npm run version:check
      - name: Lint code
        run: npm run lint
      - name: Lint commits
        run: npm run lint:commits -- --from origin/${{ github.base_ref }}
