name: Test splunk-otel-js Docker image

on:
  pull_request:
    paths:
      - 'Dockerfile'
      - '.github/workflows/test-docker-image.yml'

jobs:
  test-image:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: docker/setup-buildx-action@v2
      - name: build container
        uses: docker/build-push-action@v4.1.1
        with:
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/ppc64le
          build-args: |
            RELEASE_VER=${{ env.GITHUB_REF_NAME }}
